apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-slave
spec:
  replicas: 10
  template:
    metadata:
      labels:
        name: locust
        role: slave
    spec:
      volumes:
      - name: locustd-volume
        configMap:
          name: locustd-configmap   
      containers:
        - name: locust
          image: heehouse1/locust:0.8.8
          env:
            - name: LOCUST_MODE
              value: slave
            - name: LOCUST_MASTER
              value: locust-master
            - name: LOCUST_LOCUSTFILE_PATH
              value: "/locust-tasks/locustfile.py"
            - name: LOCUST_TARGET_HOST
              value: "http://10.0.0.58:80"
          volumeMounts:
          - name: locustd-volume
            mountPath: /locust-tasks
